apiVersion: gitkube.sh/v1alpha1
kind: Remote
metadata:
  creationTimestamp: null
  name: eks-remote
  namespace: default
spec:
  authorizedKeys:
  - |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLk6Eyd+4iNBZN3iWJLzI4C2Dwuj35fSf6vFff2OzFcJf7HLr0kBTsFNeLtwINIttADt8fZ9p4d/PKIuaS486FDTo7LKcIqrQ+oDGGfGhIbpCB83ynW1InU8FdrJBjF+kp0+ygwki0cPEAWXUukgofK01GUlA4JU0R2sIPgYAzVLHWLI5dFiHx4SkcJgYuBXweY2/6QToOa2QjdPZ5Bu9b9/MjvTVlVerV5Z7JzQ5EP1DH4/GBJ4PGguRAQ0+pw7NLlIi0CAHxPVJg1lBF3Vgv2V85DDL+rU21eAiYMjtFHWlA/ApTd4mKT5kSZj0fRujoefeTyA+goHBMFIeTPs+k4beszgqE1zF1H6/OZsCbbslKUb3IajAcPslIbRDYeCszc42kSc8EgpdlkumBXPwqbmBQCfY8YqSwDyPQP/S1ivEaDHsRt4tD9gg14UpcZEjwfk4ZN9APO5j2PmEDgmzrJ0DGc5NWuNqVz1GCNMpc78XBVNfmYdTyqTarSPK3bO0ddW8wMnIpYEDng+k6MUWmEDFUnT8XraR9/cb7odAUvy/8iAhdNu80B3D/R7wDWpFBGop8dPIO05inJ5TSOE6nIbxMv8GAAau0/vbwfm+0tSYSak6hbZweFLtYqFCzjxnjNVAB4U88fitEDBCYGInGNVCbd673n8OBAqHVaPuxGw== desaivarshil5@gmail.com
  deployments:
  - containers:
    - dockerfile: Dockerfile
      name: www
      path: ./
    name: www
  manifests:
    helm: {}
    path: ./manifests
  registry:
    credentials:
      secretKeyRef:
        key: ""
status:
  remoteUrl: ""
  remoteUrlDesc: ""
